# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 657bb56b674854f52945b68805ece80046b4e4215f316c8df6ecad9eafec456772380d76d61108ae39a3cd91617df0f594de9def95cbd5abeb447ef1f6112b51

test:
  secret_key_base: f28a02b061c46bf871f5f4f57701f79e34e7483051b8f94b8b8af7b491fb640c34127696ae84a6ad75ee3bec63d6a87837fbc87b44532f385138902d90c68add

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
